// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nft/wasm_message.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GameNftDenomIssueMessage struct {
	Nft *NftDenomIssueMessage `protobuf:"bytes,1,opt,name=nft,proto3" json:"nft,omitempty"`
}

func (m *GameNftDenomIssueMessage) Reset()         { *m = GameNftDenomIssueMessage{} }
func (m *GameNftDenomIssueMessage) String() string { return proto.CompactTextString(m) }
func (*GameNftDenomIssueMessage) ProtoMessage()    {}
func (*GameNftDenomIssueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f267daf04bac102, []int{0}
}
func (m *GameNftDenomIssueMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameNftDenomIssueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameNftDenomIssueMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GameNftDenomIssueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameNftDenomIssueMessage.Merge(m, src)
}
func (m *GameNftDenomIssueMessage) XXX_Size() int {
	return m.Size()
}
func (m *GameNftDenomIssueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GameNftDenomIssueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GameNftDenomIssueMessage proto.InternalMessageInfo

func (m *GameNftDenomIssueMessage) GetNft() *NftDenomIssueMessage {
	if m != nil {
		return m.Nft
	}
	return nil
}

type NftDenomIssueMessage struct {
	IssueDenom *DenomIssueMessage `protobuf:"bytes,1,opt,name=issue_denom,json=issueDenom,proto3" json:"issue_denom,omitempty"`
}

func (m *NftDenomIssueMessage) Reset()         { *m = NftDenomIssueMessage{} }
func (m *NftDenomIssueMessage) String() string { return proto.CompactTextString(m) }
func (*NftDenomIssueMessage) ProtoMessage()    {}
func (*NftDenomIssueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f267daf04bac102, []int{1}
}
func (m *NftDenomIssueMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftDenomIssueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftDenomIssueMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftDenomIssueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftDenomIssueMessage.Merge(m, src)
}
func (m *NftDenomIssueMessage) XXX_Size() int {
	return m.Size()
}
func (m *NftDenomIssueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NftDenomIssueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NftDenomIssueMessage proto.InternalMessageInfo

func (m *NftDenomIssueMessage) GetIssueDenom() *DenomIssueMessage {
	if m != nil {
		return m.IssueDenom
	}
	return nil
}

type DenomIssueMessage struct {
	DenomId string `protobuf:"bytes,1,opt,name=denom_id,json=denomId,proto3" json:"denom_id,omitempty" yaml:"denom_id"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
	Schema  string `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty" yaml:"schema"`
}

func (m *DenomIssueMessage) Reset()         { *m = DenomIssueMessage{} }
func (m *DenomIssueMessage) String() string { return proto.CompactTextString(m) }
func (*DenomIssueMessage) ProtoMessage()    {}
func (*DenomIssueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f267daf04bac102, []int{2}
}
func (m *DenomIssueMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomIssueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomIssueMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomIssueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomIssueMessage.Merge(m, src)
}
func (m *DenomIssueMessage) XXX_Size() int {
	return m.Size()
}
func (m *DenomIssueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomIssueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DenomIssueMessage proto.InternalMessageInfo

func (m *DenomIssueMessage) GetDenomId() string {
	if m != nil {
		return m.DenomId
	}
	return ""
}

func (m *DenomIssueMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DenomIssueMessage) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

type GameNftMintMessage struct {
	Nft *NftMintMessage `protobuf:"bytes,1,opt,name=nft,proto3" json:"nft,omitempty"`
}

func (m *GameNftMintMessage) Reset()         { *m = GameNftMintMessage{} }
func (m *GameNftMintMessage) String() string { return proto.CompactTextString(m) }
func (*GameNftMintMessage) ProtoMessage()    {}
func (*GameNftMintMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f267daf04bac102, []int{3}
}
func (m *GameNftMintMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GameNftMintMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GameNftMintMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GameNftMintMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameNftMintMessage.Merge(m, src)
}
func (m *GameNftMintMessage) XXX_Size() int {
	return m.Size()
}
func (m *GameNftMintMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GameNftMintMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GameNftMintMessage proto.InternalMessageInfo

func (m *GameNftMintMessage) GetNft() *NftMintMessage {
	if m != nil {
		return m.Nft
	}
	return nil
}

type NftMintMessage struct {
	MintNft *MintMessage `protobuf:"bytes,1,opt,name=mint_nft,json=mintNft,proto3" json:"mint_nft,omitempty"`
}

func (m *NftMintMessage) Reset()         { *m = NftMintMessage{} }
func (m *NftMintMessage) String() string { return proto.CompactTextString(m) }
func (*NftMintMessage) ProtoMessage()    {}
func (*NftMintMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f267daf04bac102, []int{4}
}
func (m *NftMintMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftMintMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftMintMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftMintMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftMintMessage.Merge(m, src)
}
func (m *NftMintMessage) XXX_Size() int {
	return m.Size()
}
func (m *NftMintMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NftMintMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NftMintMessage proto.InternalMessageInfo

func (m *NftMintMessage) GetMintNft() *MintMessage {
	if m != nil {
		return m.MintNft
	}
	return nil
}

type MintMessage struct {
	DenomId   string `protobuf:"bytes,1,opt,name=denom_id,json=denomId,proto3" json:"denom_id,omitempty" yaml:"denom_id"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`
	URI       string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty" yaml:"uri"`
	Data      string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty" yaml:"data"`
	Recipient string `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty" yaml:"recipient"`
}

func (m *MintMessage) Reset()         { *m = MintMessage{} }
func (m *MintMessage) String() string { return proto.CompactTextString(m) }
func (*MintMessage) ProtoMessage()    {}
func (*MintMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f267daf04bac102, []int{5}
}
func (m *MintMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MintMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MintMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MintMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintMessage.Merge(m, src)
}
func (m *MintMessage) XXX_Size() int {
	return m.Size()
}
func (m *MintMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MintMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MintMessage proto.InternalMessageInfo

func (m *MintMessage) GetDenomId() string {
	if m != nil {
		return m.DenomId
	}
	return ""
}

func (m *MintMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MintMessage) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

func (m *MintMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *MintMessage) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func init() {
	proto.RegisterType((*GameNftDenomIssueMessage)(nil), "cosmosgaminghub.nibiru.nft.GameNftDenomIssueMessage")
	proto.RegisterType((*NftDenomIssueMessage)(nil), "cosmosgaminghub.nibiru.nft.NftDenomIssueMessage")
	proto.RegisterType((*DenomIssueMessage)(nil), "cosmosgaminghub.nibiru.nft.DenomIssueMessage")
	proto.RegisterType((*GameNftMintMessage)(nil), "cosmosgaminghub.nibiru.nft.GameNftMintMessage")
	proto.RegisterType((*NftMintMessage)(nil), "cosmosgaminghub.nibiru.nft.NftMintMessage")
	proto.RegisterType((*MintMessage)(nil), "cosmosgaminghub.nibiru.nft.MintMessage")
}

func init() { proto.RegisterFile("nft/wasm_message.proto", fileDescriptor_8f267daf04bac102) }

var fileDescriptor_8f267daf04bac102 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0x3a, 0xba, 0xed, 0x55, 0x30, 0x16, 0x0a, 0x8a, 0x2a, 0x94, 0x20, 0x73, 0x18,
	0x4c, 0x5a, 0xcc, 0xc6, 0x0d, 0x71, 0xaa, 0x90, 0xa0, 0x87, 0xf5, 0x10, 0xc1, 0x85, 0x03, 0x95,
	0xd3, 0x3a, 0x99, 0xa5, 0xd9, 0x0e, 0xb1, 0x03, 0xf4, 0x5b, 0x20, 0xf1, 0xa5, 0x38, 0xee, 0xc8,
	0x29, 0x42, 0x2d, 0x9f, 0x20, 0x9f, 0x00, 0xd9, 0x6e, 0xb7, 0x6a, 0x1b, 0xe3, 0xc4, 0xed, 0xf9,
	0xfd, 0x7f, 0xef, 0xff, 0x9e, 0xfe, 0x92, 0xe1, 0xa1, 0xc8, 0x34, 0xfe, 0x42, 0x14, 0x1f, 0x73,
	0xaa, 0x14, 0xc9, 0x69, 0x5c, 0x94, 0x52, 0x4b, 0xbf, 0x3f, 0x91, 0x8a, 0x4b, 0x95, 0x13, 0xce,
	0x44, 0x7e, 0x52, 0xa5, 0xb1, 0x60, 0x29, 0x2b, 0xab, 0x58, 0x64, 0xba, 0xdf, 0xcb, 0x65, 0x2e,
	0x2d, 0x86, 0x4d, 0xe5, 0x26, 0xfa, 0x8f, 0x72, 0x29, 0xf3, 0x53, 0x8a, 0x49, 0xc1, 0x30, 0x11,
	0x42, 0x6a, 0xa2, 0x99, 0x14, 0x6a, 0xa9, 0xee, 0x3b, 0x3f, 0x9c, 0x12, 0x45, 0xf1, 0xa7, 0x8a,
	0x96, 0x33, 0xfc, 0xf9, 0x30, 0xa5, 0x9a, 0x1c, 0xe2, 0x82, 0xe4, 0x4c, 0x58, 0xd8, 0xb1, 0xe8,
	0x23, 0x04, 0x6f, 0x08, 0xa7, 0xa3, 0x4c, 0xbf, 0xa6, 0x42, 0xf2, 0xa1, 0x52, 0x15, 0x3d, 0x76,
	0xd7, 0xf9, 0x03, 0x68, 0x8b, 0x4c, 0x07, 0xde, 0x63, 0xef, 0x69, 0xf7, 0xe8, 0x79, 0xfc, 0xf7,
	0x2b, 0xe3, 0xeb, 0xc6, 0x13, 0x33, 0x8c, 0x32, 0xe8, 0x5d, 0xeb, 0x3d, 0x82, 0x2e, 0x33, 0xef,
	0xf1, 0xd4, 0x48, 0xcb, 0x1d, 0x07, 0x37, 0xed, 0xb8, 0xba, 0x00, 0xac, 0x83, 0xed, 0xa3, 0xef,
	0x1e, 0xec, 0x5e, 0xdd, 0x12, 0xc3, 0x96, 0xf5, 0x1f, 0xb3, 0xa9, 0x5d, 0xb1, 0x3d, 0xb8, 0xdf,
	0xd4, 0xd1, 0xce, 0x8c, 0xf0, 0xd3, 0x97, 0x68, 0xa5, 0xa0, 0x64, 0xd3, 0x96, 0xc3, 0xa9, 0xff,
	0x04, 0x36, 0x04, 0xe1, 0x34, 0xb8, 0x65, 0xd9, 0x9d, 0xa6, 0x8e, 0xba, 0x8e, 0x35, 0x5d, 0x94,
	0x58, 0xd1, 0x7f, 0x06, 0x1d, 0x35, 0x39, 0xa1, 0x9c, 0x04, 0x6d, 0x8b, 0xed, 0x36, 0x75, 0x74,
	0xc7, 0x61, 0xae, 0x8f, 0x92, 0xce, 0xaa, 0x00, 0x7f, 0x99, 0xee, 0x31, 0x13, 0x7a, 0x75, 0xd5,
	0xab, 0xf5, 0x5c, 0xf7, 0xff, 0x91, 0xeb, 0xda, 0xa0, 0x4b, 0xf4, 0x1d, 0xdc, 0xbd, 0xe4, 0x37,
	0x80, 0x2d, 0xce, 0x84, 0x1e, 0x5f, 0x98, 0xee, 0xdd, 0x64, 0xba, 0xee, 0xb8, 0x69, 0x06, 0x47,
	0x99, 0x46, 0xbf, 0x3d, 0xe8, 0xae, 0x7b, 0xfe, 0x97, 0xe4, 0xf6, 0xa0, 0x5d, 0x95, 0x6c, 0x19,
	0xdb, 0x83, 0x79, 0x1d, 0xb5, 0xdf, 0x27, 0xc3, 0xa6, 0x8e, 0xc0, 0xa1, 0x55, 0xc9, 0x50, 0x62,
	0x08, 0xe3, 0x36, 0x25, 0x9a, 0x04, 0x1b, 0x97, 0xdd, 0x4c, 0x17, 0x25, 0x56, 0xf4, 0x8f, 0x60,
	0xbb, 0xa4, 0x13, 0x56, 0x30, 0x2a, 0x74, 0x70, 0xdb, 0x92, 0xbd, 0xa6, 0x8e, 0xee, 0x39, 0xf2,
	0x5c, 0x42, 0xc9, 0x05, 0x36, 0x78, 0xfb, 0x63, 0x1e, 0x7a, 0x67, 0xf3, 0xd0, 0xfb, 0x35, 0x0f,
	0xbd, 0x6f, 0x8b, 0xb0, 0x75, 0xb6, 0x08, 0x5b, 0x3f, 0x17, 0x61, 0xeb, 0x43, 0x9c, 0x33, 0x6d,
	0x82, 0x9a, 0x48, 0x8e, 0x5d, 0x78, 0x07, 0xe7, 0xe9, 0x61, 0x97, 0x1e, 0xfe, 0x8a, 0xcd, 0x0f,
	0xd6, 0xb3, 0x82, 0xaa, 0xb4, 0x63, 0xff, 0xcf, 0x8b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x63, 0xab, 0x60, 0xd5, 0x03, 0x00, 0x00,
}

func (m *GameNftDenomIssueMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameNftDenomIssueMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GameNftDenomIssueMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nft != nil {
		{
			size, err := m.Nft.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWasmMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NftDenomIssueMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftDenomIssueMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftDenomIssueMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IssueDenom != nil {
		{
			size, err := m.IssueDenom.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWasmMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DenomIssueMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomIssueMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomIssueMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Schema) > 0 {
		i -= len(m.Schema)
		copy(dAtA[i:], m.Schema)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.Schema)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DenomId) > 0 {
		i -= len(m.DenomId)
		copy(dAtA[i:], m.DenomId)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.DenomId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GameNftMintMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GameNftMintMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GameNftMintMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nft != nil {
		{
			size, err := m.Nft.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWasmMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NftMintMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftMintMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftMintMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MintNft != nil {
		{
			size, err := m.MintNft.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWasmMessage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MintMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MintMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MintMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.URI) > 0 {
		i -= len(m.URI)
		copy(dAtA[i:], m.URI)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.URI)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DenomId) > 0 {
		i -= len(m.DenomId)
		copy(dAtA[i:], m.DenomId)
		i = encodeVarintWasmMessage(dAtA, i, uint64(len(m.DenomId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWasmMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovWasmMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GameNftDenomIssueMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nft != nil {
		l = m.Nft.Size()
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	return n
}

func (m *NftDenomIssueMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IssueDenom != nil {
		l = m.IssueDenom.Size()
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	return n
}

func (m *DenomIssueMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DenomId)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	l = len(m.Schema)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	return n
}

func (m *GameNftMintMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nft != nil {
		l = m.Nft.Size()
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	return n
}

func (m *NftMintMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MintNft != nil {
		l = m.MintNft.Size()
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	return n
}

func (m *MintMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DenomId)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	l = len(m.URI)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovWasmMessage(uint64(l))
	}
	return n
}

func sovWasmMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWasmMessage(x uint64) (n int) {
	return sovWasmMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GameNftDenomIssueMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameNftDenomIssueMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameNftDenomIssueMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nft", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Nft == nil {
				m.Nft = &NftDenomIssueMessage{}
			}
			if err := m.Nft.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftDenomIssueMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftDenomIssueMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftDenomIssueMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueDenom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.IssueDenom == nil {
				m.IssueDenom = &DenomIssueMessage{}
			}
			if err := m.IssueDenom.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DenomIssueMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomIssueMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomIssueMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Schema", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Schema = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GameNftMintMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GameNftMintMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GameNftMintMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nft", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Nft == nil {
				m.Nft = &NftMintMessage{}
			}
			if err := m.Nft.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftMintMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftMintMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftMintMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintNft", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MintNft == nil {
				m.MintNft = &MintMessage{}
			}
			if err := m.MintNft.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MintMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWasmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MintMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MintMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWasmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWasmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWasmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWasmMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWasmMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWasmMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWasmMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWasmMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWasmMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWasmMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWasmMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWasmMessage = fmt.Errorf("proto: unexpected end of group")
)
