version: '3'

services:
  nibirudnode0:
    container_name: nibirudnode0
    image: "cosmos-gaminghub/nibirudnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-nibirud.log}
    volumes:
      - ./build:/nibirud:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  nibirudnode1:
    container_name: nibirudnode1
    image: "cosmos-gaminghub/nibirudnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-nibirud.log}
    volumes:
      - ./build:/nibirud:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  nibirudnode2:
    container_name: nibirudnode2
    image: "cosmos-gaminghub/nibirudnode"
    environment:
      - ID=2
      - LOG=${LOG:-nibirud.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/nibirud:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  nibirudnode3:
    container_name: nibirudnode3
    image: "cosmos-gaminghub/nibirudnode"
    environment:
      - ID=3
      - LOG=${LOG:-nibirud.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/nibirud:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
