name: Genesis Test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  verify-signatures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: gentx-validation
        run: |
          make install
          bash -x ./scripts/start.sh
